version: '2'
services:
  web:
    build: ./app-backend
    command: python ttbcore/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app-backend/:/ttb-core
    ports:
      - "8080:8080"
    links:
      - db

  frontend:
    build: ./app-frontend
    command: npm run start
    volumes:
      - ./app-frontend:/usr/src/app
    ports:
      - "4200:4200"
      - "49153:49153"
    links:
      - web

  db:
    image: postgres
    ports:
      - "5432:5432"
